//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_consultation_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        public int meetint_id { get; set; }
        public string exp_handle { get; set; }
        public string address { get; set; }
        public string day { get; set; }
        public int time_start { get; set; }
        public int time_end { get; set; }
        public int is_valid { get; set; }
        public string user_handle { get; set; }
    }
}
