//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace online_consultation_sys
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbUser
    {
        public string handle { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public string e_mail { get; set; }
        public string gender { get; set; }
    }
}
